[tool.poetry]
name = "scaledp"
version = "0.2.2rc11"
description = "ScaleDP is a library for processing documents using Apache Spark and LLMs"
authors = ["Mykola Melnyk <mykola@stabrise.com>"]
repository = "https://github.com/StabRise/scaledp"
homepage = "https://stabrise.com/scaledp/"
license = "AGPL-3.0"
readme = "README.md"
packages = [{include = "scaledp"}]
include = ["scaledp/resource/*"]

[tool.poetry.dependencies]
python = "^3.10"
pyspark = "3.5.3"
pillow = "^10.4.0"
imagesize = "1.4.1"
pandas = "^2.2.2"
pytesseract = "0.3.13"
pytest = "^7.4.4"
PyMuPDF = "1.24.11"
numpy = "^1.26.4"
pyarrow = "17.0.0"
filelock = "*"
surya-ocr = {version = "0.8.1", optional = true}
easyocr = {version = "1.7.2", optional = true}
python-doctr = {version = "0.10.0", optional = true}
transformers = {version = "^4.36.0", optional = true}
torchvision= {version= ">=0.18.0", source = "pytorch_cpu", optional = true}
torch =  [
    #{version = "==2.2.0", platform = "darwin", optional = true },
    {version = ">=2.4.1", source = "pytorch_cpu", platform = "linux", optional = true}
]
dspy = {version = "2.5.43", optional = true}
levenshtein = "^0.26.1"
pydantic = ">=1.8.0"
huggingface-hub = "^0.27.0"
tenacity = "^9.0.0"
openai = "^1.58.0"

[tool.poetry.extras]
ml = ["transformers", "torch"]
ocr = ["easyocr", "python-doctr", "surya-ocr"]
llm = ["dspy"]

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[project]
name = "scaledp"
dependencies = [
    "pytest"
]


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
pytest-spark = "0.6.0"
jupyter = "^1.1.1"
ipykernel = "^6.29.5"
tesserocr = "2.7.1"
pytest-resource-path = "1.3.0"
coverage = "7.6.4"
pytest-cov="5.0.0"
transformers = "^4.36.0"
torchvision= {version= ">=0.18.0", source = "pytorch_cpu"}
python-doctr  = "0.10.0"
surya-ocr = "0.8.1"

ultralytics = "^8.3.40"

[build-system]
requires = ["poetry-core<2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["F405"]

[tool.ruff]
line-length = 99