[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cba-events"
version = "0.1.14"
description = "A Python package for handling cba events"
authors = [{ name = "Crystal Ball", email = "your.email@example.com" }]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "confluent-kafka>=2.0.0",
    "dataclasses-json>=0.5.7"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]