[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pydgeon"
version = "v0.2.1"
description = "A Python library for simplifying sending emails using smtplib"
authors = [{ name = "GeeseCanHonk", email = "GeeseCanHonk@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
dependencies = []
requires-python = ">=3.7"

[project.urls]
Homepage = "https://pypi.org/project/pydgeon/"
Repository = "https://github.com/GeeseCanHonk/pydgeon"
Issues = "https://github.com/GeeseCanHonk/pydgeon/issues"
