[package]
name = "betterproto-rust-codec"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "betterproto2_rust_codec"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.37"
indoc = "2.0.5"
prost = { version = "0.13.4", features = ["no-recursion-limit"] }
pyo3 = { version = "0.21.0", features = ["abi3-py37", "extension-module", "chrono"] }
thiserror = "2.0.11"
