[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aims_chain"
version = "0.1.0"
description = "A package for finding minimum energy path and transition state."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

# List your dependencies here
dependencies = [
    "numpy",
    "scipy"
]

[project.entry-points.console_scripts]
runchain = "aimsChain.tools.runchain:main"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[project.urls]
repository = "https://gitlab.com/FHI-aims-club/aims-chain"
