[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-pg-notify"
version = "1.0.1"
description = "Simplifies listening to and sending notifications using PostgreSQL"
authors = [
    { name = "D S Sanjaya", email = "dssanjay55555@gmail.com" }
]
license = { text = "MIT License" }
readme = "README.md"
keywords = ["postgresql", "listen", "notify", "python", "database", "notification", "postgres"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "asyncpg==0.30.0",
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["py_pg_notify"]
namespaces = false

[project.optional-dependencies]
dev = [
    "pytest==8.3.3",
]

[project.urls]
Homepage = "https://github.com/DSSanjaya5/py-pg-notify"