[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jthreads"
version = "1.0.0"
authors = [
    { name="Cristian Trohin", email="cristi.trohin@gmail.com" },
]
description = "A package providing some simple extensions of the Thread class for Python."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ctrohin/jthreads"
Issues = "https://github.com/ctrohin/jthreads/issues"