[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "incognito-anonymizer"
version = "0.0.2"
description = "A module to anonymize french text data" 
readme = "README.md"
licence="MIT"
dependencies = [
  "pydantic",
  "regex",
  "flashtext",
]
authors = [
  {name="Arthur Lamard", email="arthur.lamard@chu-brest.fr"}
]

[project.optional-dependencies]
dev= ["pytest", "pytest-cov", "twine", "build"]
