[build-system]
requires = ["hatchling>=1.17.0"]
build-backend = "hatchling.build"

[project]
name = "omega_agents"
version = "0.1.3"
description = "A scalable ReAct-based multi-agent framework."
authors = [
  {name="Arpit Sharma", email="arpitsh018@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "requests>=2.28",
  "pydantic>=1.10"
]

[project.optional-dependencies]
test = [
  "pytest>=7.0",
  "pytest-cov>=3.0",
]

[project.scripts]
omega_agents = "omega_agents.main:cli"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
packages = ["src/omega_agents"]

[tool.hatch.build.targets.wheel]
packages = ["src/omega_agents"]