[build-system]
requires = ["hatchling==1.26.3","pkginfo>1.10"]  
build-backend = "hatchling.build"
[project]
name = "EDS_mod"
version = "1.0.4"
authors = [
  { name="Jonathan M Smith", email="jmsmith@quantum-curiosity.com" },
]
description = "A package for Data Science"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/laserchemist/EDS_module"
Issues = "https://github.com/laserchemist/EDS_module/issues"
