[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ug_gemeinde"
version = "1.2.9"
description = "Adressverwaltung fÃ¼r Gemeinden"
readme = "README.md"
licence = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "ugbib_divers",
    "ugbib_modell",
    "ugbib_tkinter",
    "ugbib_werkzeug",
    "Pillow",
    "psycopg2-binary",
    "PyYAML",
    "rich",
]
autors = [
    {name = "Ulrich Goebel", email = "ulrich@fam-goebel.de"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ug_gemeinde"]
# include = ["src/ug_gemeinde/*.yaml"]

# [tool.hatch.build.sources]
# "src" = "ug_gemeinde"

[tool.hatch.entry-points.console_scripts]
Gemeinde = "ug_gemeinde.Gemeinde:main"
