[project]
name = "hotspot-socks-proxy"
version = "3.2.0"
description = "SOCKS proxy for routing traffic through WiFi interface"
authors = [
    { name = "tadeasf", email = "business@tadeasfort.com" },
]
dependencies = [
    "typer>=0.15.1",
    "prompt-toolkit>=3.0.48",
    "rich>=13.9.4",
    "psutil>=5.9.0",
    "pyperclip>=1.9.0",
    "tomli>=2.2.1",
    "dnspython>=2.7.0",
    "mkdocs-gen-files>=0.5.0",
    "loguru>=0.7.3",
]
readme = "README.md"
requires-python = ">= 3.10"

[project.scripts]
hotspot-proxy = "hotspot_socks_proxy.cmd.cli:app"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.build]
includes = [
    "src/hotspot_socks_proxy",
]
package-dir = "src"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "D203",
    "UP036",
    "RUF022",
    "D212",
    "ANN001",
    "ANN002",
    "ANN201",
    "ANN401",
    "BLE001",
    "TRY300",
    "COM812",
    "ISC001",
    "FBT001",
    "S603",
    "C901",
]

[tool.ruff.lint.isort]
known-first-party = [
    "hotspot_socks_proxy",
]
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "google"
