[project]
name = "fastapi-agents"
version = "0.1.27"
description = "A FastAPI extension for integrating common AI agent frameworks."
readme = "README.md"
classifiers = [ "Development Status :: 3 - Alpha", "Framework :: FastAPI", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.12", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
keywords = [ "fastapi", "ai", "agents", "smolagents", "llama-index", "pydantic-ai",]
requires-python = ">=3.12"
dependencies = [ "fastapi>=0.115.6",]
[[project.authors]]
name = "Blair Hudson"
email = "blairhudson@users.noreply.github.com"

[build-system]
requires = [ "hatchling==1.26.3",]
build-backend = "hatchling.build"

[dependency-groups]
dev = [ "httpx>=0.27.2", "ipykernel>=6.29.5", "mkdocs>=1.6.1", "mkdocs-git-committers-plugin-2>=2.4.1", "mkdocs-git-revision-date-localized-plugin>=1.3.0", "mkdocs-include-markdown-plugin>=7.1.2", "mkdocs-jupyter>=0.25.1", "mkdocs-material>=9.5.49", "mkdocstrings[python]>=0.27.0", "pymdown-extensions>=10.14", "pytest>=8.3.4", "pytest-cov>=6.0.0", "toml>=0.10.2",]

[project.urls]
Repository = "https://github.com/blairhudson/fastapi-agents"

[project.license]
file = "LICENSE"

[project.optional-dependencies]
llama-index = [ "llama-index>=0.12.10",]
pydantic-ai = [ "pydantic-ai>=0.0.18",]
smolagents = [ "smolagents>=1.2.2", "litellm>=1.57.8",]
uvicorn = [ "uvicorn>=0.34.0",]
security = [ "python-multipart>=0.0.20",]
crewai = [ "crewai>=0.95.0",]

[project.scripts]
bump-version = "scripts.version:bump_patch"
get-version = "scripts.version:get_version"
