
[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


# ----------------------------------------- setuptools -------------------------------------------
[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true


# ----------------------------------------- Project Metadata -------------------------------------
#
[project]
version = "0.0.0.dev430"
name = "ControlMan"
dependencies = [
    "packaging >= 23.2, < 24",
    "trove-classifiers >= 2024.9.12",
    "jsonschema >= 4.23, < 5",
    "referencing == 0.35.1",
    "jsonpath-ng == 1.6.1",
    "ruamel.yaml == 0.18.6",
    "Jinja2 >= 3, < 4",
    "PyLinks == 0.0.0.dev70",
    "LoggerMan == 0.0.0.dev87",
    "PySerials == 0.0.0.dev60",
    "GitTidy == 0.0.0.dev85",
    "PkgData == 0.0.0.dev5",
    "PyShellMan == 0.0.0.dev47",
    "PySyntax == 0.0.0.dev5",
    "ExceptionMan == 0.0.0.dev57",
    "MDit == 0.0.0.dev57",
    "JSONSchemata == 0.0.0.dev56",
    "VersionMan == 0.0.0.dev249",
    "HTMP == 0.0.0.dev5",
    "LicenseMan == 0.0.0.dev44",
]
requires-python = ">=3.10"
