[project]
name = "random-wikipedia-article-yuhan"
version = "0.1.1"
description = "A simple tool to display random Wikipedia articles"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "requests",
]
requires-python = ">=3.8"

[project.scripts]
random-wikipedia-article = "wiki_displayer.wiki:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["wiki_displayer"]