[build-system]
requires = ["hatchling>=1.17.0"]
build-backend = "hatchling.build"

[project]
name = "omega_agents"
version = "0.2.2"
description = "OmegaAgents is a scalable ReAct-based multi-agent framework designed for rapid solution development. It enables LLMs and agents to dynamically create and coordinate sub-agents during inference, mimicking human-like task distribution and collaboration. With built-in tools, parallel processing, and ephemeral memory management, it streamlines complex problem-solving through autonomous agent orchestration and structured output validation."
authors = [
  {name="Arpit Sharma", email="arpitsh018@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "requests>=2.28",
  "pydantic>=1.10",
  "pydantic-settings>=2.0.0",
  "google-search-results>=2.4.2",
  "openai",
  "jsonschema",
  "aiohttp"
]

[project.optional-dependencies]
test = [
  "pytest>=7.0",
  "pytest-cov>=3.0",
]

[project.scripts]
omega_agents = "omega_agents.main:cli"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
packages = ["src/omega_agents"]

[tool.hatch.build.targets.wheel]
packages = ["src/omega_agents"]