[tool.poetry]
name = "ki2-mqtty-cli"
version = "1.4.0"
description = "Command-line utility designed to facilitate the interconnection between serial devices and an MQTT server. This project is based on the `mqtty` library and allows simple configuration using a TOML file."
authors = ["Adrien KERFOURN <ak.sitecontact@gmail.com>"]
readme = "README.md"
packages = [{include = "mqtty_cli"}]
license = "MIT"

[tool.poetry.scripts]
mqtty-cli = "mqtty_cli.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
tomli = "^2.2.1"
typing-extensions = "^4.12.2"
ki2-python-utils = "^0.3.5"
aiomqtt = "^2.3.0"
pydantic = "^2.10.4"
pyserial = "^3.5"
ki2-mqtty = "^1.4.0"


[tool.poetry.group.dev.dependencies]
pyserial = "^3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
