[tool.poetry]
name = "mlregistry"
version = "1.1.0"
description = "Register, retrieve and get metadata from machine learning models."
authors = ["Eric Cardozo <eric.m.cardozo@mi.unc.edu.ar>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/mapache-software/ml-registry"


[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.tests.dependencies]
pytest = "^8.3.3"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocstrings = "^0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
