[project]
name = "humannum"
dynamic = []
description = "Human Friendly Numbers"
readme = "README.md"
authors = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9.0,<4.0"
dependencies = [
    "humanfriendly>=10.0",
]
version = "1.2.0"

[project.urls]
Homepage = "https://github.com/nbiotcloud/humannum"
Documentation = "https://humannum.readthedocs.io/en/stable/"
"Bug Tracker" = "https://github.com/nbiotcloud/humannum/issues"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.version]
source = "scm"

[tool.pdm.dev-dependencies]
format = [
    "pre-commit>=3.5.0",
]
test = [
    "contextlib-chdir>=1.0.2",
    "coveralls>=3.3.1",
    "pytest-cov>=5.0.0",
    "test2ref>=0.4.2",
]
checktypes = [
    "mypy>=1.9.0",
]
doc = [
    "mkdocs-include-markdown-plugin>=6.0.5",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-material>=9.5.18",
    "mkdocstrings-python>=1.9.2",
    "mkdocs-click>=0.8.1",
]

[tool.pdm.build]
includes = [
    "src/humannum",
]

[tool.ruff]
line-length = 120
fix = true
target-version = "py39"

[tool.ruff.lint]
select = [
    "I",
    "F",
    "E",
    "W",
    "D",
    "YTT",
    "B",
    "Q",
    "T10",
    "INT",
    "PL",
    "PIE",
    "PYI",
    "TID",
    "ISC",
    "TCH",
    "C",
    "C4",
    "PGH",
    "RUF",
    "S102",
    "NPY002",
    "PERF",
    "FLY",
    "G",
    "UP",
    "S",
    "PTH",
    "RET",
    "RSE",
]
ignore = [
    "PLR0913",
    "D102",
    "D203",
    "D212",
    "D402",
    "D406",
    "D200",
    "D107",
    "D105",
    "UP038",
    "S101",
]

[tool.ruff.lint.per-file-ignores]
"test_*" = [
    "PLR2004",
    "ARG001",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
addopts = "    --cov humannum\n    --cov-report term\n    --cov-report html\n    --doctest-glob=docs/*\n    --doctest-modules\n    --ignore=noxfile.py\n    --ignore-glob=tests/testdata*\n    --log-level=DEBUG\n    --junitxml=report.xml\n"
filterwarnings = [
    "error",
]

[tool.coverage.report]
exclude_lines = [
    "return NotImplemented",
    "raise NotImplementedError()",
    "pragma: no cover",
    "assert False",
]

[tool.mypy]
disable_error_code = "misc"
ignore_missing_imports = true
overrides = [
    { module = "tests.*", allow_untyped_defs = true },
]
